name = "SeededAlignment"
uuid = "481cdb6f-2cd4-4f16-9496-25db73f63c93"
authors = ["anton083 <anton.oresten42@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
