name = "SeededAlignment"
uuid = "481cdb6f-2cd4-4f16-9496-25db73f63c93"
authors = ["anton083 <anton.oresten42@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
BioSequences = "3"
Distributions = "0.25"
LinearAlgebra = "1"
Random = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Distributions", "Random"]
